import {randomToken,sha256,cookies,response,originOk,getSession} from '../../_auth.js';
function safeName(s){return String(s||'document.pdf').replace(/[^a-zA-Z0-9._ -]/g,'_').slice(0,120)}
export async function onRequest(context){
 const {request,env}=context;if(!originOk(request))return response({error:'Invalid request origin.'},403);const s=await getSession(context);if(!s||!s.email_verified_at)return response({error:'Please log in.'},401);const parts=Array.isArray(context.params.id)?context.params.id:(context.params.id?[context.params.id]:[]),id=parts[0]||'';
 try{
  if(request.method==='GET'&&!id){const rows=await env.DB.prepare('SELECT id,name,type,mime,size,created_at FROM documents WHERE user_id=?1 ORDER BY created_at DESC LIMIT 100').bind(s.user_id).all();return response({documents:rows.results||[]})}
  if(request.method==='POST'&&!id){const fd=await request.formData(),file=fd.get('file');if(!(file instanceof File))return response({error:'PDF file is required.'},400);if(file.size>25*1024*1024)return response({error:'Saved documents are limited to 25 MB per file.'},413);const mime=file.type||'application/pdf';if(mime!=='application/pdf')return response({error:'Only PDF documents can be saved.'},400);const docId=randomToken(16),name=safeName(fd.get('name')||file.name||'YoqArt document.pdf'),type=String(fd.get('type')||'Document').slice(0,40),key=`users/${s.user_id}/${docId}/${name}`;await env.BUCKET.put(key,await file.arrayBuffer(),{httpMetadata:{contentType:'application/pdf',contentDisposition:`attachment; filename="${name.replace(/"/g,'')}"`}});await env.DB.prepare('INSERT INTO documents(id,user_id,name,type,r2_key,mime,size,created_at) VALUES(?,?,?,?,?,?,?,?)').bind(docId,s.user_id,name,type,key,'application/pdf',file.size,Date.now()).run();return response({ok:true,id:docId})}
  if(id&&request.method==='GET'){const row=await env.DB.prepare('SELECT id,name,mime,r2_key FROM documents WHERE id=?1 AND user_id=?2').bind(id,s.user_id).first();if(!row)return response({error:'Document not found.'},404);const obj=await env.BUCKET.get(row.r2_key);if(!obj)return response({error:'File not found.'},404);const h=new Headers();h.set('Content-Type',row.mime||'application/pdf');h.set('Content-Disposition',`attachment; filename="${row.name.replace(/"/g,'')}"`);return new Response(obj.body,{headers:h})}
  if(id&&request.method==='DELETE'){const row=await env.DB.prepare('SELECT r2_key FROM documents WHERE id=?1 AND user_id=?2').bind(id,s.user_id).first();if(!row)return response({error:'Document not found.'},404);await env.BUCKET.delete(row.r2_key);await env.DB.prepare('DELETE FROM documents WHERE id=?1 AND user_id=?2').bind(id,s.user_id).run();return response({ok:true})}
  return response({error:'Not found.'},404);
 }catch(e){console.error(e);return response({error:e.message||'Document service error.'},500)}
}
