import express from 'express';
import cors from 'cors';
import multer from 'multer';
import fs from 'fs/promises';
import os from 'os';
import path from 'path';
import crypto from 'crypto';
import {spawn} from 'child_process';

const app=express();
const PORT=process.env.PORT||3000;
const MAX_MB=Number(process.env.MAX_UPLOAD_MB||50);
const MAX_SECONDS=Number(process.env.MAX_MEDIA_SECONDS||900);
const upload=multer({dest:path.join(os.tmpdir(),'yoqart-upload'),limits:{fileSize:MAX_MB*1024*1024}});
const allowedMedia=u=>{try{const x=new URL(u);return ['youtube.com','www.youtube.com','m.youtube.com','youtu.be','instagram.com','www.instagram.com'].includes(x.hostname.toLowerCase())||x.hostname.toLowerCase().endsWith('.instagram.com')}catch{return false}};
const run=(cmd,args)=>new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let out='',err='';p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);p.on('error',reject);p.on('close',code=>resolve({code,out,err}))});
app.use(cors());
app.use(express.json({limit:'100kb'}));
app.use(express.static('public',{extensions:['html']}));
app.get('/api/health',(req,res)=>res.json({ok:true,service:'YoqArt backend',version:'2.0.0'}));
async function cleanup(...xs){for(const x of xs)await fs.rm(x,{recursive:true,force:true}).catch(()=>{});}
async function conversion(req,res,kind){const f=req.file;if(!f)return res.status(400).json({error:'Please upload a PDF file.'});const dir=path.join(os.tmpdir(),'yoqart-convert',crypto.randomUUID());await fs.mkdir(dir,{recursive:true});const out=path.join(dir,kind==='word'?'yoqart-converted.docx':'yoqart-converted.xlsx');try{const r=await run('python3',['convert.py',kind,f.path,out]);if(r.code!==0){console.error(r.err);await cleanup(dir,f.path);return res.status(502).json({error:'PDF conversion failed. Please try a different PDF.'})}await fs.stat(out);res.download(out,kind==='word'?'yoqart-converted.docx':'yoqart-converted.xlsx',()=>cleanup(dir,f.path));}catch(e){await cleanup(dir,f.path);res.status(500).json({error:'Server conversion error.'})}}
app.post('/api/convert/pdf-to-word',upload.single('file'),(req,res)=>conversion(req,res,'word'));
app.post('/api/convert/pdf-to-excel',upload.single('file'),(req,res)=>conversion(req,res,'excel'));
app.post('/api/protect-pdf',upload.single('file'),async(req,res)=>{const f=req.file,pw=String(req.body?.password||'');if(!f)return res.status(400).json({error:'Please upload a PDF file.'});if(!pw)return res.status(400).json({error:'Please provide a password.'});const dir=path.join(os.tmpdir(),'yoqart-protect',crypto.randomUUID());await fs.mkdir(dir,{recursive:true});const out=path.join(dir,'yoqart-protected.pdf');try{const r=await run('gs',['-sDEVICE=pdfwrite','-dCompatibilityLevel=1.4','-dNOPAUSE','-dQUIET','-dBATCH',`-sOwnerPassword=${pw}`,`-sUserPassword=${pw}`,'-dEncryptionR=3','-dKeyLength=128',`-sOutputFile=${out}`,f.path]);if(r.code!==0){await cleanup(dir,f.path);return res.status(502).json({error:'PDF protection failed.'})}res.download(out,'yoqart-protected.pdf',()=>cleanup(dir,f.path))}catch(e){await cleanup(dir,f.path);res.status(500).json({error:'Protection engine is unavailable.'})}});
app.post('/api/compress-pdf',upload.single('file'),async(req,res)=>{const f=req.file;if(!f)return res.status(400).json({error:'Please upload a PDF file.'});const dir=path.join(os.tmpdir(),'yoqart-compress',crypto.randomUUID());await fs.mkdir(dir,{recursive:true});const out=path.join(dir,'yoqart-compressed.pdf');const quality=['screen','ebook','printer','prepress'].includes(req.body?.quality)?req.body.quality:'ebook';try{const r=await run('gs',['-sDEVICE=pdfwrite','-dCompatibilityLevel=1.4',`-dPDFSETTINGS=/${quality}`,'-dNOPAUSE','-dQUIET','-dBATCH',`-sOutputFile=${out}`,f.path]);if(r.code!==0){await cleanup(dir,f.path);return res.status(502).json({error:'PDF compression failed.'})}let st=await fs.stat(out),src=await fs.stat(f.path);if(st.size>=src.size&&quality!=='screen'){const retry=path.join(dir,'yoqart-compressed-screen.pdf');const rr=await run('gs',['-sDEVICE=pdfwrite','-dCompatibilityLevel=1.4','-dPDFSETTINGS=/screen','-dNOPAUSE','-dQUIET','-dBATCH',`-sOutputFile=${retry}`,f.path]);if(rr.code===0){const rs=await fs.stat(retry);if(rs.size<st.size){await fs.rename(retry,out);st=rs}}}res.setHeader('X-YoqArt-Original-Bytes',String(src.size));res.setHeader('X-YoqArt-Compressed-Bytes',String(st.size));res.setHeader('X-YoqArt-Reduced',String(st.size<src.size));res.download(out,'yoqart-compressed.pdf',()=>cleanup(dir,f.path));}catch(e){await cleanup(dir,f.path);res.status(500).json({error:'Compression engine is unavailable.'})}});
app.post('/api/download',async(req,res)=>{const {url,quality='Best available',format='mp4'}=req.body||{};if(!allowedMedia(url))return res.status(400).json({error:'Unsupported or invalid YouTube/Instagram URL.'});if(format!=='mp4')return res.status(400).json({error:'Only MP4 is enabled.'});const h=quality==='1080p'?1080:quality==='720p'?720:quality==='480p'?480:quality==='360p'?360:1080;const dir=path.join(os.tmpdir(),'yoqart-media',crypto.randomUUID());await fs.mkdir(dir,{recursive:true});const out=path.join(dir,'video.%(ext)s');try{const r=await run('yt-dlp',['--no-playlist','--restrict-filenames','--max-filesize',`${MAX_MB}M`,'--match-filter',`duration <= ${MAX_SECONDS}`,'-f',`bv*[height<=${h}][ext=mp4]+ba[ext=m4a]/b[height<=${h}][ext=mp4]/b[height<=${h}]`,'--merge-output-format','mp4','-o',out,'--print','after_move:filepath',url]);if(r.code!==0){const msg=(r.err||'Unable to process URL.').split('\n').filter(Boolean).slice(-1)[0];await cleanup(dir);return res.status(502).json({error:msg})}const file=r.out.trim().split(/\r?\n/).filter(Boolean).pop();if(!file){await cleanup(dir);return res.status(502).json({error:'Media file was not created.'})}await fs.stat(file);res.download(file,'yoqart-video.mp4',()=>cleanup(dir));}catch(e){await cleanup(dir);res.status(500).json({error:'Media processing error.'})}});
app.use((req,res)=>res.sendFile(path.resolve('public/index.html')));
app.listen(PORT,()=>console.log(`YoqArt server listening on ${PORT}`));
