const enc=new TextEncoder();
function response(data,status=200,headers={}){return Response.json(data,{status,headers})}
function originOk(req){const o=req.headers.get('Origin');return !o||o===new URL(req.url).origin}
function randomId(){const a=new Uint8Array(16);crypto.getRandomValues(a);return [...a].map(x=>x.toString(16).padStart(2,'0')).join('')}
async function body(req){try{return await req.json()}catch{return {}}}
function clean(v,max){return String(v??'').trim().slice(0,max)}
function esc(s){return String(s).replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
async function rateLimit(env,key,limit=5,windowMs=600000){const now=Date.now();const row=await env.DB.prepare('SELECT window_start,count FROM api_rate_limits WHERE key=?1').bind(key).first();if(!row||now-row.window_start>=windowMs){await env.DB.prepare('INSERT INTO api_rate_limits(key,window_start,count) VALUES(?1,?2,1) ON CONFLICT(key) DO UPDATE SET window_start=excluded.window_start,count=1').bind(key,now).run();return true}if(row.count>=limit)return false;await env.DB.prepare('UPDATE api_rate_limits SET count=count+1 WHERE key=?1').bind(key).run();return true}
function ip(req){return req.headers.get('CF-Connecting-IP')||req.headers.get('X-Forwarded-For')||'unknown'}
async function verifyCaptcha(req,env,token,action){const secret=env.RECAPTCHA_SECRET_KEY;if(!secret)return true;if(!token)return false;const r=await fetch('https://www.google.com/recaptcha/api/siteverify',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded'},body:new URLSearchParams({secret,response:token,remoteip:ip(req)})});if(!r.ok)return false;const d=await r.json();return !!d.success && (!action || !d.action || d.action===action) && (!env.RECAPTCHA_MIN_SCORE || Number(d.score||0)>=Number(env.RECAPTCHA_MIN_SCORE))}
async function sendMail(env,to,subject,html,replyTo){const key=env.RESEND_API_KEY;if(!key)throw Error('Email service is not configured.');const from=env.AUTH_FROM_EMAIL||'YoqArt <noreply@yoqart.in>';const payload={from,to,subject,html};if(replyTo)payload.reply_to=replyTo;const r=await fetch('https://api.resend.com/emails',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify(payload)});if(!r.ok)throw Error('Unable to send email right now.');return r}

export async function onRequest({request,env}){if(request.method!=='POST')return response({error:'Method not allowed.'},405);if(!originOk(request))return response({error:'Invalid request origin.'},403);const b=await body(request);if(String(b.website||'').trim())return response({ok:true,message:'Thanks.'});if(!(await rateLimit(env,'feedback:'+ip(request),5,600000)))return response({error:'Too many requests. Please try again later.'},429);const rating=Number(b.rating),subject=clean(b.subject,160),message=clean(b.message,5000);if(!Number.isInteger(rating)||rating<1||rating>5||subject.length<2||message.length<5)return response({error:'Please provide a rating, subject and message.'},400);if(!(await verifyCaptcha(request,env,b.recaptchaToken,'feedback')))return response({error:'CAPTCHA verification failed. Please try again.'},400);const html=`<div style="font-family:Arial,sans-serif"><h2>New YoqArt Feedback</h2><p><b>Rating:</b> ${rating}/5</p><p><b>Subject:</b> ${esc(subject)}</p><p><b>Message:</b><br>${esc(message).replace(/\n/g,'<br>')}</p><p style="color:#68738a;font-size:12px">Submitted: ${new Date().toISOString()}</p></div>`;try{await sendMail(env,'feedback@yoqart.in',`YoqArt Feedback — ${rating}/5 — ${subject}`,html)}catch(e){console.error(e);return response({error:'Feedback could not be delivered right now. Please try again later.'},502)}return response({ok:true,message:'Thanks for your feedback!'},201)}